### ISSUE TITLE
Error in the documentation

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#13]
In the documentation, the example value of these arguments is swapped:
```
  --title_annotation="description"
  --message_annotation="summary"
```
I did not check if the default values (in the code) are right.

**Comment by DRuggeri** [comment]
Thanks for the catch, @ngosang - I will fix and release this adjustment. The code was indeed incorrect, so this will be a 'major' bump because it could technically break configurations!
