### ISSUE TITLE
Publish Docker images for more architectures

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#15]
Related  #14

You should publish more images => https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/master/.github/workflows/release.yml#L128

Just some example, I don't know archs supported by go => `linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x`

**Comment by DRuggeri** [comment]
Hi, @ngosang. I'm not opposed, but there's a matrix of support that needs to be maintained:
* The [golang](https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/de1975bb880e8583f9794bc1b3b9a71f4095e789/.github/workflows/release.yml#L73) os/arch combo
* The [linux](https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/de1975bb880e8583f9794bc1b3b9a71f4095e789/.github/workflows/release.yml#L117) arch reported in `uname -m`
* The [docker/build-push-actions](https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/de1975bb880e8583f9794bc1b3b9a71f4095e789/.github/workflows/release.yml#L135) supported versions

I'm more than happy to add these if you can identify the different permutations of each value and toss a pull request out there. In practice, I find that nearly all users are able to be served with:
* AMD64 (64-bit x86)
* ARM64 (newer ARMv8 instruction set)
* ARM (ARMv7 and prior instruction set)

**Comment by ngosang** [comment]
@DRuggeri thank you. This is enough for me. I tested x64 and arm architectures and both are right!
