### ISSUE TITLE
Update Docker-compose documentation

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#16]
Docker image must be in lower case => https://github.com/DRuggeri/alertmanager_gotify_bridge#docker-compose

`ghcr.io/druggeri/alertmanager_gotify_bridge:latest`

**Comment by DRuggeri** [comment]
OK, sure - this is done.

**Comment by ngosang** [comment]
@DRuggeri please, replace the tag `master` with `latest`. `master`  does not exists.
