### ISSUE TITLE
Missing ca-ceritficates causing error

### ISSUE THREAD

**Issue by CubicrootXYZ** [DRuggeri/alertmanager_gotify_bridge#19]
I am getting a `x509: certificate signed by unknown authority` error on any dispatch. This might happen as I am using Let's Encrypt TLS certificates for the pushbits (gotify for matrix) instance for which the root certs are missing. 

According to [this](https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/326) (kind of random) issue I found on GitHub this might be related to the missing `apk add --no-cache ca-certificates && update-ca-certificates` in the image.

**Comment by DRuggeri** [comment]
Thanks for the heads up, @CubicrootXYZ - that does sound about right. I'm pushing a new change right now that should address this! Please reopen the issue if you still have any issues :-)

**Comment by mikkel1156** [comment]
Ran into this issue today. Ended up mounting the hosts certificates to get around it. Also using a Let's Encrypt certificate.

Tried getting a shell inside the container to see if I could run the `apk` commands manually to test, but couldn't get a shell with neither bash, ash, nor sh.
