### ISSUE TITLE
NUT_EXPORTER_WEB_AUTH_PASSWORD should be documented

### ISSUE THREAD

**Issue by v4rakh** [DRuggeri/alertmanager_gotify_bridge#24]
I think `NUT_EXPORTER_WEB_AUTH_PASSWORD` should be documented or maybe we could add a `AUTH_PASSWORD` and react to that instead?

**Comment by DRuggeri** [comment]
Thanks, @v4rakh - I've gone ahead and added this note in the help output of my other repo (nut_exporter) and kicked off a release
