### ISSUE TITLE
[feature request] add linux arm64 binary

### ISSUE THREAD

**Issue by ngosang** [DRuggeri/alertmanager_gotify_bridge#3]
Gotify, Prometheus, Grafana, Alertmanager... all provide builds for arm64. It's becoming popular.

**Comment by DRuggeri** [comment]
Sure, @ngosang  - happy to do so. I've updated the 0.3.0 release and future versions will include arm64 for linux.

**Comment by ngosang** [comment]
It's working perfect. Thank you very much!
