### ISSUE TITLE
gotify doesn't support 'text/html' (extended details)

### ISSUE THREAD

**Issue by disconn3ct** [DRuggeri/alertmanager_gotify_bridge#31]
The dev is very specific about it [here](https://gotify.net/docs/msgextras#clientdisplay) (emphasis from the original)
> The message should be rendered as markdown. **HTML should be ignored.**

As expected, it is not rendered correctly by the app or the web.

**Comment by DRuggeri** [comment]
Ah, interesting. This was added in a PR by @CubicrootXYZ back in '21. In the original PR description, it mentioned that HTML is supported in the docs - but then the doc linked doesn't seem to support that after all (history indicates the line about HTML being ignored has always been there). Can you say more about what doesn't get rendered properly? If the HTML is ignored (which I assume just means the tags are stripped but not the contents), I think the only thing that shouldn't wouldn't work is the [go to source](https://github.com/DRuggeri/alertmanager_gotify_bridge/blob/master/main.go#L469-L475) link.

**Comment by disconn3ct** [comment]
It renders as a solid text blob, with html tags shown. The text blob is especially annoying on mobile, but the mobile client does auto-link the url.

**Comment by disconn3ct** [comment]
As a followup to how it renders, it also messes up the mobile notification click. Clicking on the notification no longer goes to the Gotify app; instead it goes to the (cluster-internal) prometheus address.

**Comment by DRuggeri** [comment]
@thomas-maurice fixed this in #32! I'm rolling the release now

**Comment by disconn3ct** [comment]
Just to close the loop, it is fixed! Thanks!
