### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by jvandenbroek** [DRuggeri/alertmanager_gotify_bridge#5]
Would it be possible to include self monitoring metrics, so we could monitor if this specific instance is up? Because i use Gotify for all my alerts, it would be nice to know the bridge is actually working. Simply adding a second alert route (eg email) and monitoring the bridge's status would cover this. Even better if also the specified Gotify URL could be monitored (gotify_url/health) with a separate metric.

**Comment by DRuggeri** [comment]
Yeah, that's a great idea @jvandenbroek. The go Prometheus exporter SDK makes it pretty easy to do this, so this bridge would just need to have an exporter embedded inside. I'll work on this when time allows. In the meantime, you could also use the prometheus blackbox_exporter to monitor this and the gotify server.

**Comment by jvandenbroek** [comment]
Yes good suggestion, was already using blackbox and now added monitoring the bridge port. Looking forward to this, no rush take your time :-)

**Comment by DRuggeri** [comment]
I had some free time this morning and pushed `v0.4.0` that adds this. Thanks again for the idea!
